### ISSUE TITLE
Missing Variations.js

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#29]
Hi, 

I'm getting the same errors as reported by @robinheidrich here #26. Checking on your ide file and recent pr/merged:

https://github.com/Tach-Yon/Tap-Tap-Adventure/blob/master/.idea/workspace.xml#L1194
https://github.com/Tach-Yon/Tap-Tap-Adventure/pull/28/files

also did a local folder search after complete clone, it is supposed to be located here, but nowhere to be found:

https://github.com/Tach-Yon/Tap-Tap-Adventure/tree/master/server/js/game/utils

Is this some sort of auto-generated file? I do think you forgot to include it in your repo, unless we are missing something out.

Thanks for sharing btw.

**Comment by Tach-Yon** [comment]
No, the file was removed a long time ago and is no longer needed, those are just dead dependencies.

**Comment by wini3d** [comment]
Ah ok,  I see now that you just removed the required js file, but there are some references pointing to it. Maybe you can just do an update?

https://github.com/Tach-Yon/Tap-Tap-Adventure/blob/master/server/js/game/entity/character/player/player.js#L80
https://github.com/Tach-Yon/Tap-Tap-Adventure/blob/master/server/js/game/entity/character/player/player.js#L494-L495

also just curious as to why you removed those doubleEXP and expMultiplier, bug issues?

Got it running now, thanks again for this awesome version! :smile:

**Comment by Tach-Yon** [comment]
@wini3d They simply were not needed, didn't have enough time with the game to grow and have events.

**Comment by wini3d** [comment]
ah I see. That's unfortunate, but thanks for clearing that up.
