### ISSUE TITLE
TMX Map Format

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#30]
Hi again @Tach-Yon, I see you also left out a source terrain.tmx map with just a sample painted hill/cave which is nice, but not the whole actual map from the game. Can this be added to the repo as a reference or guide as well? If not, I would assume you still use the BQ mapping convention or did you change or added custom fields that is required on this game?

**Comment by Tach-Yon** [comment]
I added custom fields in the /tools/ directory. Certain areas as PVP or whatever have been modified, I don't remember all of them, but it is slightly different from that of BQ. Terrain.tmx is simply a test I was working on to draw maps faster but failed and left it there. Open map.json with Tiled and you'll have the entirety of the TTA map, you can modify it and simply compile it with 

`./exportmap.js ./tmx/map.json`
in the directory `/tools/maps/`

I used JSON format for the map to not have to export to JSON upon making minor modifications to the .tmx file, and it was becoming quite tedious after some time.

**Comment by wini3d** [comment]
Aha great, thanks got it now. :smiley: That is really nifty and fast!
