### ISSUE TITLE
Inventory Count or Rendering Issues

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#32]
@Tach-Yon, while getting to test the game on my local installation, I have noticed some weird inventory count or rendering issues. Most of the time if my inventory is full and I drop the item one by one, the image of that particular item is still left inside the inventory.

Here's another weird and recent issue.

![inventory](https://cloud.githubusercontent.com/assets/12629729/22973923/d62a2584-f3ba-11e6-954f-9e5bf65df2ba.png)

I have tried this on your actual server, but it does not produce the same errors. Maybe I need to add or progress more..

**Comment by Polarcraft** [comment]
You must have modified the code as this doesn't happen on our test servers.
