### ISSUE TITLE
Some animated sprites stops playing when player is moving

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#34]
Not sure if this is an isolated case and I have tried this on your live server, each time the player walks, some sprites like the campfire animation will stop and continue when player is standing still again.

**Comment by Tach-Yon** [comment]
It is due to the camera being centred upon the player. Having those animated whilst the player is moving would cause some huge performance drops, especially when using canvas as our engine. Perhaps I will focus on those in the future when necessary.
