### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by bostrot** [Tach-Yon/Tap-Tap-Adventure#36]
I followed the guide in the readme but end up getting the error "Unable to connect to the game server, please try again.". What did I do wrong?

**Comment by Tach-Yon** [comment]
This repository is deprecated. I will not be providing any fixes to the state of the server. Please refer to Kaetram if you want an up-to-date version of TTA.

https://github.com/udeva/Kaetram

**Comment by lolisakio** [comment]
so how can i fix this problem?

**Comment by Tach-Yon** [comment]
@lolisakio post you’re server and client configuration files

**Comment by lolisakio** [comment]
where is client configuration file?

**Comment by Tach-Yon** [comment]
The data folder.

**Comment by lolisakio** [comment]
thanx... i solved this problem!

**Comment by Tach-Yon** [comment]
Best of luck!
