### ISSUE TITLE
How can I get tmx file?

### ISSUE THREAD

**Issue by xavierzhao** [Tach-Yon/Tap-Tap-Adventure#39]
I am new to HTML5 game development, and I want understanding full HTML5 game development process through **Tap-Tap-Adventure**, but I cannot found **tmx** file from the source code, can you provide source of tmx file for more detail? thanks

**Comment by Tach-Yon** [comment]
Look closer, TMX can be converted to JSON. Open map.json with Tiled.

**Comment by xavierzhao** [comment]
@Tach-Yon Where is **map.json**? I cannot open **[world_client.json](https://raw.githubusercontent.com/Tach-Yon/Tap-Tap-Adventure/master/client/data/maps/world_client.json)** with Tiled.

**Comment by Tach-Yon** [comment]
Tools folder.

**Comment by xavierzhao** [comment]
I'm sorry, I'm stupid, but I still can't find it. Can I trouble you again?
![image](https://user-images.githubusercontent.com/1573662/31213471-85c132a0-a96c-11e7-9f4c-bd55de435df7.png)

**Comment by Tach-Yon** [comment]
Literally read the folder names... tools/map/data

**Comment by xavierzhao** [comment]
I've still not found what I'm looking for.
![image](https://user-images.githubusercontent.com/1573662/31213797-ea3b90d0-a96d-11e7-9e88-f5ab6c9d3e22.png)

**Comment by Tach-Yon** [comment]
Map file dumped in the recent commit. It is in the folder I've listed above.

**Comment by xavierzhao** [comment]
I saw it, thanks
