### ISSUE TITLE
HTTPS on the server side

### ISSUE THREAD

**Issue by tgraupne** [Tach-Yon/Tap-Tap-Adventure#41]
Hi,

I was wondering, how hard it would be to change the backend web server to https?
We have a hackathon project going on right now and we kinda need the communication over https.

Best wishes, Tom

**Comment by Tach-Yon** [comment]
I have tried to do a HTTPS implementation a while ago but I do not have a valid back-end server to try it with. Nonetheless, you would have to modify the networking, swap the port to 443 (config.json) and do the same for the login and registration API (if you still want to keep it). Best of luck with your project.

**Comment by Tach-Yon** [comment]
Oh and almost forgot, swap `ws` with `wss` in `socket.js` in the client side.

**Comment by tgraupne** [comment]
Thanks for your feedback but unfortunately, I don't really understand everything you just mentioned. Where would I have to change something for the login- and registration-api?

**Comment by Tach-Yon** [comment]
That would be the `handleIntro` method in `incoming.js` - server sided.

**Comment by tgraupne** [comment]
I'm now able to connect to the game with https but unfortunately, "every player is dying seconds after joining the game" 😅 
This is really weird, what could be the reason for this now?

**Comment by Tach-Yon** [comment]
They’re not dying. They are being disconnected and I recall having this issue. You have to lengthen the time SSL allows a connection to remain open. I’m pretty sure it automatically times out after a second or so.

**Comment by tgraupne** [comment]
Ok, we got https to work, thanks
