### ISSUE TITLE
Websocket conflicts

### ISSUE THREAD

**Issue by tgraupne** [Tach-Yon/Tap-Tap-Adventure#42]
Hi, me again, sorry for bothering you.
I just have a quick question...

Do you think that we could run into conflicts when we try to integrate another tool into your app which also uses web sockets?

The problem is, that we are not very familiar with working with web sockets and node and js ... and we encounter strange problems when playing the game and using our tool.

In a sentence, we try to integrate voice chat into your app :-) 
And our voice chat service also uses web sockets and now we don't know if the two systems effect each other.

**Comment by Tach-Yon** [comment]
I’m not really able to give a concise answer, I’d have to see the code. But my guess is to create an independent server running alongside the current one, and integrate the voice chat client side. Then simply connect and output the details to the user chat.

**Comment by tgraupne** [comment]
That is what we are trying to do.
We just integrated our sdk at the client side.

One of our developers found this:

"where does the js/utils/utils.js come from?

is that you guys or something you pulled from online?

Thats something we pulled from online
I mean.. its the source code of this opensource game

yeah so that file is polyfilling bind

What does that mean?

and the bind call behaving differently is what is causing the jserror
so its replacing the browsers builtin bind call with a different one

most likely this game was built before bind was available in browsers
since bind was an es5 addition

Shouldnt the polyfill first see if bind() exists?

the good news is you can probably just delete these lines in util.js"

**Comment by Tach-Yon** [comment]
Was about to suggest adding a `if Function.prototype.bind`. It is something I overlooked and never gave much thought. I’ll do the modifications in a bit, do consider that the code may have been there before TTA was rewritten, and it is still necessary in case older devices require it. But yea.. thanks for pointing that out..
