### ISSUE TITLE
Game screen does not fit in browser

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#45]
I noticed this current version has its display region slightly taller/bigger than the client browser. The inventory and other buttons at the bottom is clipped out and not visible. This issue does not exist on previous versions though.

**Comment by Tach-Yon** [comment]
What device are you using?

**Comment by wini3d** [comment]
I'm just using Chrome browser (Windows). What I'm trying to do is setup for desktop browsers with the default canvas size like BrowserQuest. 

What I did was set the zoom to 1.0. The only problem that I am having right now is the canvas and html mouse/cursor coordinates are out of sync. I would just like to configure it the same with the original browserquest and opt out of full width and height.

Something like this?

![maxresdefault](https://i.ytimg.com/vi/exRSudpVytU/maxresdefault.jpg)

**Comment by Tach-Yon** [comment]
Make sure you move the canvas in CSS as well. I coded the entire game with the zoom function intrinsically implemented into it. As for the mouse positioning check out `setCoords` in `input.js` and readapt that function with that of the original BrowserQuest.

**Comment by wini3d** [comment]
Thanks. I have not really dug up the original bq code so perhaps you could provide those specific parts that needs to change?

**Comment by Polarcraft** [comment]
Hey, I understand you are trying to do some of your changes, but we do not support this meaning we don't provide support for doing these things. We may assist you with what you wish to do, but that is at our discretion and we may close any tickets requesting such topics.

**Comment by wini3d** [comment]
Ok, thanks guys. 

@Tach-Yon `setCoords` in `input.js` works ok. Thanks.
