### ISSUE TITLE
Suggestion Vocations(Classes)

### ISSUE THREAD

**Issue by Brenosolutions** [Tach-Yon/Tap-Tap-Adventure#48]
Hello Tach-Yon!

**Suggestion Vocations(Classes)**
Create 4 vocations to choose a preferred when creating a new character account

**Vocations names**
Knight, Paladin, Druid, Sorcerer.

**functions**
**Knight** = Warrior
**Paladin** = Arrow
**Druid** -  Mage nature
**Sorcerer** - Mage arcane master of the black arts

**More information about vocations**
https://www.tibiawiki.com.br/wiki/Knight
https://www.tibiawiki.com.br/wiki/paladin
https://www.tibiawiki.com.br/wiki/druid
https://www.tibiawiki.com.br/wiki/sorcerer

**Comment by Tach-Yon** [comment]
The game was initially intended to have no classes and be completely customizable to some extent to the player. Though I suppose we should have a poll about this.

**Comment by Brenosolutions** [comment]
Thank you!

**Comment by Brenosolutions** [comment]
Check out this browserquest
http://www.orientation.auvergnerhonealpes.fr/jeu/client/
have option to choose avatar.
it would be interesting to put this to choose vocations.

thank you!

**Comment by Tach-Yon** [comment]
I’ve played orientation before, got some of their tilesheet designs implemented into TTA.

**Comment by eric256** [comment]
Maybe they could be like a starter pack. An initial stat pack to start you off by picking a class/vocation.  Kind of like picking a back story.  Then having your game play modify and control your character development.

You might start a druid but that just gives your backstory and some foundational characteristics. You might rapidly become a powerful knight or mage based one your game play.

**Comment by Tach-Yon** [comment]
Please repost this in the `suggestions` section on the forum. It is pointless to keep an issue open like this.
