### ISSUE TITLE
Set Game Screen Height

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#55]
Hi, how do I decrease the game screen height to give some space on a browser setup? I see the height is currently set to around 530px and would like it just to be at ~500px. 

Thanks.

**Comment by Tach-Yon** [comment]
You cannot change the screen height unless you modify the camera and border dimensions altogether.

**Comment by wini3d** [comment]
Thanks. Can you give some file references for me to check out? I would assume this is not related to the tmx or json maps?
