### ISSUE TITLE
NPC dialog too fast when using key down/arrow keys

### ISSUE THREAD

**Issue by wini3d** [Tach-Yon/Tap-Tap-Adventure#56]
For some reason when talking to npcs or doing actions that involves arrow keys (keydown/hold), the key repeat rate is too fast to catch up what the npc is displaying. Even tapping it skips a line or two. Is this intentional or maybe a bug?

**Comment by Tach-Yon** [comment]
Most likely a bug

**Comment by wini3d** [comment]
Ok thanks, for added info, I tested it both on Chrome and Firefox with same results.

**Comment by Tach-Yon** [comment]
Fixed
