### ISSUE TITLE
Website linked in Repo description does not work

### ISSUE THREAD

**Issue by robflop** [Tach-Yon/Tap-Tap-Adventure#57]
Hi,

just found this repo and wanted to check out the site and noticed the one linked in the repo's description/header section does not work.

Refering to this one: ![](https://i.robflop.me/S4wongSZ.png)

I get this error on Vivaldi/Chrome: ![](https://i.robflop.me/ldpFoHzJ.png).

The main domain, without using the ``www`` subdomain, works, so I assume it's just faulty configuration of the ``www`` subdomain's DNS.

**Comment by Tach-Yon** [comment]
Yep that must be a minor NGINX misconfiguration, I’ll fix it shortly.

**Comment by Tach-Yon** [comment]
Fixed
