### ISSUE TITLE
Cant attack after picking up item

### ISSUE THREAD

**Issue by dioniss4u** [Tach-Yon/Tap-Tap-Adventure#60]
After you pick up a potion or item you cannot attack anything....

**Comment by Tach-Yon** [comment]
Problema cu server-ul, o sa ma interesez ;)

**Comment by dioniss4u** [comment]
am incercat eu sa ii fac un debug dar inca nu mi-am dat seama d unde e
;)

**Comment by Tach-Yon** [comment]
Am resolvat-o, era din `input.js`, incercam sa fac WSAD sa mearga si am uitat ceva.

Download the last commit :P
