### ISSUE TITLE
Error Self.world.open

### ISSUE THREAD

**Issue by Sigri44** [Tach-Yon/Tap-Tap-Adventure#64]
Hi,

I have test the game locally, on offline mode, on a virtual machine, and after 5 minute of play, i have this error.

I lauch 5 times again, and there is always the same error.

![image](https://user-images.githubusercontent.com/9304947/35269803-6106cd54-002d-11e8-9375-60c9745ab430.png)

Thx

**Comment by Sigri44** [comment]
EDIT : The problem comes, among other things, when we try to talk to the left banker !

**Comment by Tach-Yon** [comment]
`self.world.open` is obviously not defined. I screwed up that when I was working on shops. It should be `self.world.shops.open`.

**Comment by Sigri44** [comment]
Ok good thx !

For future release/problem : 

server/js/game/entity/character/player/handler.js:89
```
- self.world.open
+ self.world.shops.open
```
