### ISSUE TITLE
Collision Grid ..

### ISSUE THREAD

**Issue by crustyclown71** [Tach-Yon/Tap-Tap-Adventure#65]
Hi. 
When Server starts to generate the Collision Grid, after a while there appears the Error:

INFO An error has occurred: Error: ENOENT: no such file or directory, open './server/data/map/collisions.json'

Where is the Problem ?

![mrdw5kw](https://user-images.githubusercontent.com/36411858/36101096-a5ae12f6-1008-11e8-95c2-37d59500e1ff.png)

**Comment by tanguyfalconnet** [comment]
Hi,

I had the same problem. 

Go to "server\js\map" and edit "map.js". Line 130 and 167 you should see path to the file "collisions.json".

As a quick correction, I put the absolute path to "colission.json".  I don't know enougth nodejs to do more ^^

But now it works.

**Comment by Tach-Yon** [comment]
I don't seem to be encountering this, what NodeJS version are you running?
