### ISSUE TITLE
Cannot get / at port 1800

### ISSUE THREAD

**Issue by stingwraith** [Tach-Yon/Tap-Tap-Adventure#69]
So I set everything up as instructed, got MySQL running and ports forwarded. When I go to http://localhost:1800 or my ddns the only thing on the page says "Cannot get /"... I'm thinking this is a directory or permissions issue but not sure how to go about fixing. Thanks.

**Comment by Polarcraft** [comment]
Are you trying to access localhost on a remote desktop or are you trying to run it on your pc for testing?

**Comment by stingwraith** [comment]
I'm accessing localhost from the PC itself and the ddns address from remote IP.

**Comment by Tach-Yon** [comment]
Did you try http://127.0.0.1:1800 ? Localhost may sometimes act up depending on the configuration of the machine.

**Comment by stingwraith** [comment]
Yes, this is definitely something else...

**Comment by Tach-Yon** [comment]
Maybe your firewall is going all over the place? This isn't a TTA related issue however. Alternatively, you can use http-server in the TTA directory and simply connect to http://127.0.0.1:8080

If that works, revive this issue, it may mean we have to pick a new port.
