### ISSUE TITLE
Create map

### ISSUE THREAD

**Issue by TorchwoodPL** [Tach-Yon/Tap-Tap-Adventure#70]
I have question, how can I create my own map?? Can I convert TMX file or something?? Is there any tutorial about it??

**Comment by Tach-Yon** [comment]
Use Tiled editor and it's recommended to save it in a JSON format as map.json. Then to compile the map (from the root directory of TTA)

Make sure you use the original map as a point of reference.

```cd tools/map
./exportmap.js ./data/map.json```
