### ISSUE TITLE
Client folders

### ISSUE THREAD

**Issue by TorchwoodPL** [Tach-Yon/Tap-Tap-Adventure#71]
Howdy,

what is a difference between content of client/img/1/, client/img/2/ and client/img/3/ directory?

TIA

**Comment by TorchwoodPL** [comment]
Also how to add new monster od npc?

**Comment by TorchwoodPL** [comment]
It would be Gretą to have some tutorials on how to add utensylia, mors, npcs etc

**Comment by TorchwoodPL** [comment]
Also it would be great to have some tuts on how to add items, mobs, npcs etc

**Comment by Polarcraft** [comment]
We don't spoon feed code, the code is here just discover the code and mess with it.
