### ISSUE TITLE
Another issue after login to game

### ISSUE THREAD

**Issue by TorchwoodPL** [Tach-Yon/Tap-Tap-Adventure#75]
On newest commit, after getting pass loggin screen, I get blank screen and error on the console:

```
Uncaught TypeError: Cannot read property 'strings' of null
    at Class.update (shop.js:61)
    at Class.resize (shop.js:53)
    at Class.resize (interface.js:53)
    at renderer.js:167
```

**Comment by Tach-Yon** [comment]
Odd, I thought I fixed this while I was working on it. Gonna look into it in a tad.

**Comment by Tach-Yon** [comment]
Yep this occurs when resizing prior to loading the game. Thanks for letting me know.

**Comment by Tach-Yon** [comment]
Fixed.
