### ISSUE TITLE
Can not Connect

### ISSUE THREAD

**Issue by Z3r0-K0ol** [Tach-Yon/Tap-Tap-Adventure#79]
when i try to log in i get this error
![screenshot 2018-04-19 at 8 53 49 am](https://user-images.githubusercontent.com/33299049/38992633-53ed9092-43af-11e8-99b7-b146a579b9e9.png)

**Comment by Tach-Yon** [comment]
What is this on, main game? Development?

**Comment by crustyclown71** [comment]
I had the same, it was an IP Conflict ^^
